### ISSUE TITLE
Exception thrown: Empty domain does not have a high bound

### ISSUE THREAD

**Issue by ross2jd** [gsdlab/chocosolver#12]
The error that I am coming across is as follows:
```
$ java -jar "C:\Users\Jordan\AppData\Roaming\Sublime Text 3\Packages\Clafer-Bin\claferchocoig.jar" --file=wire_debug.js --prettify --repl
Exception in thread "main" org.clafer.ir.IrException: Emtpy domain does not have a high bound.
        at org.clafer.domain.EmptyDomain.getHighBound(EmptyDomain.java:32)
        at org.clafer.ast.compiler.AstCompiler$ExpressionCompiler.compileDecl(AstCompiler.java:1569)
        at org.clafer.ast.compiler.AstCompiler$ExpressionCompiler.visit(AstCompiler.java:1609)
        at org.clafer.ast.compiler.AstCompiler$ExpressionCompiler.visit(AstCompiler.java:877)
        at org.clafer.ast.AstQuantify.accept(AstQuantify.java:36)
        at org.clafer.ast.compiler.AstCompiler$ExpressionCompiler.compile(AstCompiler.java:887)
        at org.clafer.ast.compiler.AstCompiler$ExpressionCompiler.compile(AstCompiler.java:899)
        at org.clafer.ast.compiler.AstCompiler$ExpressionCompiler.access$100(AstCompiler.java:877)
        at org.clafer.ast.compiler.AstCompiler.compile(AstCompiler.java:289)
        at org.clafer.ast.compiler.AstCompiler.compile(AstCompiler.java:160)
        at org.clafer.ast.compiler.AstCompiler.compile(AstCompiler.java:155)
        at org.clafer.compiler.ClaferCompiler.compile(ClaferCompiler.java:210)
        at REPL.runREPL(REPL.java:114)
        at Main.main(Main.java:116)
```

It happens when I have a model like such:

```
enum Type = Input | Output

abstract Pin
    rating -> Rating
    type -> Type // A pin has some type (input or output)
    connectedWire -> Wire ? // A pin can only have one connected wire
    [(this in connectedWire.endpoint) <=> connectedWire]

    // We have a connected wire always, if its an input pin. This is because we may not
    // utilize some output pins on devices.
    [(type = Input) => connectedWire]

abstract Wire
    endpoint -> Pin 2..* // The endpoints of the wire
    	[this.connectedWire = parent]

    // There must be one and only one output Pin for the wire
    [one ep : endpoint | ep.type = Output]

    // All endpoints of the wire must have the same rating.
    [all disj a; b : endpoint | a.rating.ref = b.rating.ref]

abstract Rating
	volt : Number
	amp : Number

ratingA : Rating
	[volt = 1]
	[amp = 1]

ratingB : Rating
	[volt = 2]
	[amp = 2]

A : Pin
	[rating = ratingA]
	[type = Input]
B : Pin
	[rating = ratingB]
	[type = Input]
ecPin : Pin +
	[type = Output]
	[connectedWire]

wire : Wire +
```

I have to set the default scope to be something large (like 10). This model will solve if you give the cardinality of ecPin to be bounded (i.e 1..3)

**Comment by JLiangWaterloo** [comment]
Can you attach the js file? When I compile it, I get complaints that "Number" is not defined. Is this a new feature?

**Comment by ross2jd** [comment]
Ah, no I just didn't include it in the file. The .js file is as follows:
```
scope({c0_Number:4, c0_Pin:3, c0_Rating:2, c0_Type:2, c0_amp:2, c0_connectedWire:3, c0_endpoint:3, c0_rating:3, c0_type:3, c0_volt:2});
defaultScope(10);
intRange(-8, 7);
stringLength(16);

c0_Number = Abstract("c0_Number");
c0_Type = Abstract("c0_Type");
c0_Pin = Abstract("c0_Pin");
c0_Wire = Abstract("c0_Wire");
c0_Rating = Abstract("c0_Rating");
c0_Input = Clafer("c0_Input").withCard(1, 1).extending(c0_Type);
c0_Output = Clafer("c0_Output").withCard(1, 1).extending(c0_Type);
c0_rating = c0_Pin.addChild("c0_rating").withCard(1, 1);
c0_type = c0_Pin.addChild("c0_type").withCard(1, 1);
c0_connectedWire = c0_Pin.addChild("c0_connectedWire").withCard(0, 1);
c0_endpoint = c0_Wire.addChild("c0_endpoint").withCard(2);
c0_volt = c0_Rating.addChild("c0_volt").withCard(1, 1).extending(c0_Number);
c0_amp = c0_Rating.addChild("c0_amp").withCard(1, 1).extending(c0_Number);
c0_ratingA = Clafer("c0_ratingA").withCard(1, 1).extending(c0_Rating);
c0_ratingB = Clafer("c0_ratingB").withCard(1, 1).extending(c0_Rating);
c0_A = Clafer("c0_A").withCard(1, 1).extending(c0_Pin);
c0_B = Clafer("c0_B").withCard(1, 1).extending(c0_Pin);
c0_ecPin = Clafer("c0_ecPin").withCard(1).extending(c0_Pin);
c0_wire = Clafer("c0_wire").withCard(1).extending(c0_Wire);
c0_Number.refTo(Int);
c0_rating.refTo(c0_Rating);
c0_type.refTo(c0_Type);
c0_connectedWire.refTo(c0_Wire);
c0_endpoint.refToUnique(c0_Pin);
c0_Pin.addConstraint(ifOnlyIf($in($this(), joinRef(join(joinRef(join($this(), c0_connectedWire)), c0_endpoint))), some(join($this(), c0_connectedWire))));
c0_Pin.addConstraint(implies(equal(joinRef(join($this(), c0_type)), global(c0_Input)), some(join($this(), c0_connectedWire))));
c0_Wire.addConstraint(one([decl([ep = local("ep")], join($this(), c0_endpoint))], equal(joinRef(join(joinRef(ep), c0_type)), global(c0_Output))));
c0_Wire.addConstraint(all([disjDecl([a = local("a"), b = local("b")], join($this(), c0_endpoint))], equal(joinRef(join(joinRef(a), c0_rating)), joinRef(join(joinRef(b), c0_rating)))));
c0_endpoint.addConstraint(equal(joinRef(join(joinRef($this()), c0_connectedWire)), joinParent($this())));
c0_ratingA.addConstraint(equal(joinRef(join($this(), c0_volt)), constant(1)));
c0_ratingA.addConstraint(equal(joinRef(join($this(), c0_amp)), constant(1)));
c0_ratingB.addConstraint(equal(joinRef(join($this(), c0_volt)), constant(2)));
c0_ratingB.addConstraint(equal(joinRef(join($this(), c0_amp)), constant(2)));
c0_A.addConstraint(equal(joinRef(join($this(), c0_rating)), global(c0_ratingA)));
c0_A.addConstraint(equal(joinRef(join($this(), c0_type)), global(c0_Input)));
c0_B.addConstraint(equal(joinRef(join($this(), c0_rating)), global(c0_ratingB)));
c0_B.addConstraint(equal(joinRef(join($this(), c0_type)), global(c0_Input)));
c0_ecPin.addConstraint(equal(joinRef(join($this(), c0_type)), global(c0_Output)));
c0_ecPin.addConstraint(some(join($this(), c0_connectedWire)));
```

**Comment by JLiangWaterloo** [comment]
Should be fixed now.
