### ISSUE TITLE
Sum type error when working with inheritance

### ISSUE THREAD

**Issue by ross2jd** [gsdlab/chocosolver#21]
Consider the following model:

```
abstract DeviceNode
	cost -> integer

abstract Motor : DeviceNode
abstract Switch : DeviceNode

B : DeviceNode
	[cost = 1]
C : Motor
	[cost = 1]
D : Switch
	[cost = 1]
```

If I were to query to the total cost of the motors and switches like:
```
totalCost -> integer
[totalCost = sum (Motor.cost, Switch.cost)]
```

A type error would produced by choco:
```
Exception in thread "main" org.clafer.ast.analysis.TypeException: Cannot sum(int)
	at org.clafer.ast.analysis.TypeAnalyzer$TypeVisitor.visit(TypeAnalyzer.java:445)
	at org.clafer.ast.analysis.TypeAnalyzer$TypeVisitor.visit(TypeAnalyzer.java:146)
	at org.clafer.ast.AstSum.accept(AstSum.java:23)
	at org.clafer.ast.analysis.TypeAnalyzer$TypeVisitor.typeCheck(TypeAnalyzer.java:158)
	at org.clafer.ast.analysis.TypeAnalyzer$TypeVisitor.visit(TypeAnalyzer.java:384)
	at org.clafer.ast.analysis.TypeAnalyzer$TypeVisitor.visit(TypeAnalyzer.java:146)
	at org.clafer.ast.AstSetTest.accept(AstSetTest.java:35)
	at org.clafer.ast.analysis.TypeAnalyzer$TypeVisitor.typeCheck(TypeAnalyzer.java:158)
	at org.clafer.ast.analysis.TypeAnalyzer$TypeVisitor.access$000(TypeAnalyzer.java:146)
	at org.clafer.ast.analysis.TypeAnalyzer.analyze(TypeAnalyzer.java:117)
	at org.clafer.ast.analysis.Analysis.analyze(Analysis.java:130)
	at org.clafer.ast.compiler.AstCompiler.<init>(AstCompiler.java:158)
	at org.clafer.ast.compiler.AstCompiler.<init>(AstCompiler.java:154)
	at org.clafer.ast.compiler.AstCompiler.compile(AstCompiler.java:176)
	at org.clafer.ast.compiler.AstCompiler.compile(AstCompiler.java:172)
	at org.clafer.compiler.ClaferCompiler.compile(ClaferCompiler.java:292)
	at org.clafer.cli.REPL.runREPL(REPL.java:114)
	at org.clafer.cli.Main.main(Main.java:123)
```

**Comment by JLiangWaterloo** [comment]
I believe "[totalCost = sum (Motor.cost, Switch.cost)]" will translate down to "sum (Motor.cost.ref ++ Switch.cost.ref)" (please verify).

Note that the union operator removes duplicates. Is this what you intended?

Anyways, I believe the constraint you are looking for is "[totalCost = sum (Motor.cost) + sum(Switch.cost)]".

**Comment by ross2jd** [comment]
Good point about the removing duplicates I wouldn't have thought about that. But still why would there be a type error when the type of Motor.cost.ref and Switch.cost.ref are both sets of integers. Wouldn't the result just be a set of integers?

**Comment by JLiangWaterloo** [comment]
The sum operator is a bit weird because it is the only operator that uses "bag" semantics.

What it does is the following (latexish syntax):

sum C is equivalent to: Sigma_{c in C} c.dref

Hence if C is a set of integers, then it cannot "dref" the elements. I can overload it to work on a set of integers as well, would that help?

The downside is that it won't catch the "bugs" you are seeing here.

**Comment by ross2jd** [comment]
Ah I see now. I don't think overriding is necessary, I think that what you have is correct. But maybe the Clafer compiler should catch this type error to guide users?

**Comment by mantkiew** [comment]
Well, it is not an error unfortunately. The user might want to eliminate duplicates in some cases. In multi-concepts work, we will have separate operators for working with multi-sets and multi-relations. In this case, you should write

```
[totalCost = sum Motor.cost + sum Switch.cost]
```
